apiVersion: apps/v1
kind: Deployment

metadata:
  name: db
  namespace: auventura

spec:
  replicas: 1

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db

    spec:
      containers:
        - name: mysql
          image: mysql:8.4

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              value: auventura

            - name: MYSQL_USER
              value: auventura

            - name: MYSQL_PASSWORD
              value: auventura123

            - name: MYSQL_ROOT_PASSWORD
              value: root123

---

apiVersion: v1
kind: Service

metadata:
  name: db
  namespace: auventura

spec:
  selector:
    app: db

  ports:
    - port: 3306
      targetPort: 3306